// Generated by Wrangler by running `wrangler types`

interface Env {
	VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
	CONNPASS_API_KEY: string;
	CF_ACCESS_CLIENT_ID: string;
	CF_ACCESS_CLIENT_SECRET: string;
}
