---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app: connpass-api-proxy
data:
  proxy.conf: |
    server {
      listen 80;
      location / {
        proxy_pass    http://connpass.com/;
      }
    }
