---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connpass-api-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connpass-api-proxy
  template:
    metadata:
      labels:
        app: connpass-api-proxy
    spec:
      containers:
      - name: connpass-api-proxy
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          readOnly: true
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config
        configMap:
          name: nginx-conf
          items:
           - key: proxy.conf
             path: proxy.conf